# frozen_string_literal: true

require_relative "test_helper"

describe "Cube" do
  before(:all) do
    @schema = Mondrian::OLAP::Schema.define do
      measures_caption 'Measures caption'

      cube 'Sales' do
        description 'Sales description'
        caption 'Sales caption'
        annotations foo: 'bar'
        table 'sales'
        visible true
        dimension 'Gender', foreign_key: 'customer_id' do
          description 'Gender description'
          caption 'Gender caption'
          visible true
          hierarchy has_all: true, primary_key: 'id' do
            description 'Gender hierarchy description'
            caption 'Gender hierarchy caption'
            all_member_name 'All Genders'
            all_member_caption 'All Genders caption'
            table 'customers'
            visible true
            level 'Gender', column: 'gender', unique_members: true,
                            description: 'Gender level description', caption: 'Gender level caption' do
              visible true
              # Dimension values SQL generated by caption_expression fails on PostgreSQL and MS SQL
              if %w(mysql oracle).include?(MONDRIAN_DRIVER)
                caption_expression do
                  sql "'dummy'"
                end
              end
            end
          end
        end
        dimension 'Customers', foreign_key: 'customer_id', annotations: {foo: 'bar'} do
          hierarchy has_all: true, all_member_name: 'All Customers', primary_key: 'id', annotations: {foo: 'bar'} do
            table 'customers'
            level 'Country', column: 'country', unique_members: true, annotations: {foo: 'bar'}
            level 'State Province', column: 'state_province', unique_members: true
            level 'City', column: 'city', unique_members: false
            level 'Name', column: 'fullname', unique_members: true
          end
        end
        calculated_member 'Non-USA', annotations: {foo: 'bar'} do
          dimension 'Customers'
          formula '[Customers].[All Customers] - [Customers].[USA]'
        end
        dimension 'Time', foreign_key: 'time_id', type: 'TimeDimension' do
          hierarchy has_all: false, primary_key: 'id' do
            table 'time'
            level 'Year', column: 'the_year', type: 'Numeric', unique_members: true, level_type: 'TimeYears'
            level 'Quarter', column: 'quarter', unique_members: false, level_type: 'TimeQuarters'
            level 'Month', column: 'month_of_year', type: 'Numeric', unique_members: false, level_type: 'TimeMonths'
          end
          hierarchy 'Weekly', has_all: false, primary_key: 'id' do
            table 'time'
            level 'Year', column: 'the_year', type: 'Numeric', unique_members: true, level_type: 'TimeYears'
            level 'Week', column: 'weak_of_year', type: 'Numeric', unique_members: false, level_type: 'TimeWeeks'
          end
        end
        calculated_member 'Last week' do
          hierarchy '[Time.Weekly]'
          formula 'Tail([Time.Weekly].[Week].Members).Item(0)'
        end
        measure 'Unit Sales', column: 'unit_sales', aggregator: 'sum', annotations: {foo: 'bar'}
        measure 'Store Sales', column: 'store_sales', aggregator: 'sum'
        measure 'Store Cost', column: 'store_cost', aggregator: 'sum', visible: false
      end
    end
    @olap = Mondrian::OLAP::Connection.create(CONNECTION_PARAMS.merge schema: @schema)
  end

  it "should get all cube names" do
    assert_equal ['Sales'], @olap.cube_names
  end

  it "should get cube by name" do
    assert_kind_of Mondrian::OLAP::Cube, @olap.cube('Sales')
  end

  it "should return nil when getting cube with invalid name" do
    assert_nil @olap.cube('invalid')
  end

  it "should get cube name" do
    assert_equal 'Sales', @olap.cube('Sales').name
  end

  it "should get cube description" do
    assert_equal 'Sales description', @olap.cube('Sales').description
  end

  it "should get cube caption" do
    assert_equal 'Sales caption', @olap.cube('Sales').caption
  end

  it "should get cube annotations" do
    assert_equal({'foo' => 'bar'}, @olap.cube('Sales').annotations)
  end

  it "should be visible" do
    assert @olap.cube('Sales').visible?
  end

  it "should not be virtual" do
    assert_equal false, @olap.cube('Sales').virtual?
  end

  describe "dimensions" do
    before(:all) do
      @cube = @olap.cube('Sales')
      @dimension_names = ['Measures', 'Gender', 'Customers', 'Time']
    end

    it "should get dimension names" do
      assert_equal @dimension_names, @cube.dimension_names
    end

    it "should get dimensions" do
      assert_equal @dimension_names, @cube.dimensions.map(&:name)
    end

    it "should get dimension by name" do
      assert_equal 'Gender', @cube.dimension('Gender').name
    end

    it "should return nil when getting dimension with invalid name" do
      assert_nil @cube.dimension('invalid')
    end

    it "should get dimension description" do
      assert_equal 'Gender description', @cube.dimension('Gender').description
    end

    it "should get dimension caption" do
      assert_equal 'Gender caption', @cube.dimension('Gender').caption
    end

    it "should get dimension full name" do
      assert_equal '[Gender]', @cube.dimension('Gender').full_name
    end

    it "should get measures dimension" do
      assert @cube.dimension('Measures').measures?
    end

    it "should get measures caption" do
      assert_equal 'Measures caption', @cube.dimension('Measures').caption
    end

    it "should get dimension type" do
      assert_equal :standard, @cube.dimension('Gender').dimension_type
      assert_equal :time, @cube.dimension('Time').dimension_type
      assert_equal :measures, @cube.dimension('Measures').dimension_type
    end

    it "should get dimension annotations" do
      assert_equal({'foo' => 'bar'}, @cube.dimension('Customers').annotations)
    end

    it "should get dimension empty annotations" do
      assert_equal({}, @cube.dimension('Gender').annotations)
    end

    it "should be visible" do
      assert @cube.dimension('Gender').visible?
    end

  end

  describe "cube hierarchies" do
    before(:all) do
      @cube = @olap.cube('Sales')
      @hierarchy_names = %w(Measures Gender Customers Time Time.Weekly)
    end

    it "should get hierarchy names" do
      assert_equal @hierarchy_names, @cube.hierarchy_names
    end

    it "should get hierarchy by name" do
      assert_equal 'Gender', @cube.hierarchy('Gender').name
    end

    it "should get hierarchy dimension name" do
      hierarchy = @cube.hierarchy('Time.Weekly')
      assert_equal 'Time', hierarchy.dimension.name
      assert_equal 'Time', hierarchy.dimension_name
    end

    it "should return nil when getting dimension with invalid name" do
      assert_nil @cube.hierarchy('invalid')
    end
  end

  describe "dimension hierarchies" do
    before(:all) do
      @cube = @olap.cube('Sales')
    end

    it "should get hierarchies" do
      hierarchies = @cube.dimension('Gender').hierarchies
      assert_equal 1, hierarchies.size
      assert_equal 'Gender', hierarchies[0].name
    end

    it "should get hierarchy description" do
      assert_equal 'Gender hierarchy description', @cube.dimension('Gender').hierarchies.first.description
    end

    it "should get hierarchy caption" do
      assert_equal 'Gender hierarchy caption', @cube.dimension('Gender').hierarchies.first.caption
    end

    it "should get hierarchy names" do
      assert_equal ['Time', 'Time.Weekly'], @cube.dimension('Time').hierarchy_names
    end

    it "should get hierarchy by name" do
      assert_equal 'Time.Weekly', @cube.dimension('Time').hierarchy('Time.Weekly').name
    end

    it "should return nil when getting hierarchy with invalid name" do
      assert_nil @cube.dimension('Time').hierarchy('invalid')
    end

    it "should get default hierarchy" do
      assert_equal 'Time', @cube.dimension('Time').hierarchy.name
    end

    it "should get hierarchy full name" do
      assert_equal '[Time]', @cube.dimension('Time').hierarchy.full_name
      assert_equal '[Time.Weekly]', @cube.dimension('Time').hierarchy('Time.Weekly').full_name
    end

    it "should get hierarchy levels" do
      assert_equal ['(All)', 'Country', 'State Province', 'City', 'Name'],
        @cube.dimension('Customers').hierarchy.levels.map(&:name)
    end

    it "should get hierarchy level names" do
      assert_equal ['Year', 'Quarter', 'Month'], @cube.dimension('Time').hierarchy.level_names
      assert_equal ['(All)', 'Country', 'State Province', 'City', 'Name'], @cube.dimension('Customers').hierarchy.level_names
    end

    it "should get hierarchy level depths" do
      assert_equal [0, 1, 2, 3, 4], @cube.dimension('Customers').hierarchy.levels.map(&:depth)
    end

    it "should get hierarchy level members count" do
      assert_equal [1, 2], @cube.dimension('Gender').hierarchy.levels.map(&:members_count)
    end

    it "should set and get hierarchy level cardinality" do
      level = @cube.dimension('Gender').hierarchy.levels.last
      level.cardinality = nil
      assert_equal Java::JavaLang::Integer::MIN_VALUE, level.cardinality
      level.cardinality = 2
      assert_equal 2, @olap.cube('Sales').dimension('Gender').hierarchy.levels.last.cardinality
      level.cardinality = nil
      assert_equal Java::JavaLang::Integer::MIN_VALUE, @olap.cube('Sales').dimension('Gender').hierarchy.levels.last.cardinality
    end

    it "should get hierarchy annotations" do
      assert_equal({'foo' => 'bar'}, @cube.dimension('Customers').hierarchy.annotations)
    end

    it "should get hierarchy empty annotations" do
      assert_equal({}, @cube.dimension('Gender').hierarchy.annotations)
    end

    it "should be visible" do
      assert @cube.dimension('Gender').hierarchies.first.visible?
    end

  end

  describe "hierarchy values" do
    before(:all) do
      @cube = @olap.cube('Sales')
    end

    it "should get hierarchy all member" do
      assert_equal true, @cube.dimension('Gender').hierarchy.has_all?
      assert_equal 'All Genders', @cube.dimension('Gender').hierarchy.all_member_name
    end

    it "should not get all member for hierarchy without all member" do
      assert_equal false, @cube.dimension('Time').hierarchy.has_all?
      assert_nil @cube.dimension('Time').hierarchy.all_member_name
    end

    it "should get hierarchy root members" do
      assert_equal ['All Genders'], @cube.dimension('Gender').hierarchy.root_members.map(&:name)
      assert_equal ['All Genders'], @cube.dimension('Gender').hierarchy.root_member_names
      assert_equal ['2010', '2011'], @cube.dimension('Time').hierarchy.root_members.map(&:name)
      assert_equal ['2010', '2011'], @cube.dimension('Time').hierarchy.root_member_names
    end

    it "should return child members for specified member" do
      assert_equal ['F', 'M'], @cube.dimension('Gender').hierarchy.child_names('All Genders')
      assert_equal(
        ["Albany", "Beaverton", "Corvallis", "Lake Oswego", "Lebanon", "Milwaukie",
        "Oregon City", "Portland", "Salem", "W. Linn", "Woodburn"],
        @cube.dimension('Customers').hierarchy.child_names('USA', 'OR'))
    end

    it "should return child members for hierarchy" do
      assert_equal ['F', 'M'], @cube.dimension('Gender').hierarchy.child_names
    end

    it "should not return child members for leaf member" do
      assert_equal [], @cube.dimension('Gender').hierarchy.child_names('All Genders', 'F')
    end

    it "should return nil as child members if parent member not found" do
      assert_nil @cube.dimension('Gender').hierarchy.child_names('N')
    end

  end

  describe "hierarchy levels" do
    before(:all) do
      @cube = @olap.cube('Sales')
    end

    it "should get level description" do
      assert_equal 'Gender level description', @cube.dimension('Gender').hierarchy.level('Gender').description
    end

    it "should get level caption" do
      assert_equal 'Gender level caption', @cube.dimension('Gender').hierarchy.level('Gender').caption
    end

    it "should get level full name" do
      assert_equal '[Gender].[Gender]', @cube.dimension('Gender').hierarchy.level('Gender').full_name
    end

    it "should return nil when getting level with invalid name" do
      assert_nil @cube.dimension('Gender').hierarchy.level('invalid')
    end

    it "should get primary hierarchy level members" do
      assert_equal ['Canada', 'Mexico', 'USA'], @cube.dimension('Customers').hierarchy.level('Country').members.map(&:name)
    end

    it "should get secondary hierarchy level members" do
      assert_equal ['2010', '2011'], @cube.dimension('Time').hierarchy('Time.Weekly').level('Year').members.map(&:name)
    end

    it "should get child level" do
      assert_equal 'State Province', @cube.dimension('Customers').hierarchy.level('Country').child_level.name
    end

    it "should get parent level" do
      assert_equal 'Country', @cube.dimension('Customers').hierarchy.level('State Province').parent_level.name
    end

    it "should get descendant level" do
      assert_equal 'City', @cube.dimension('Customers').hierarchy.level('Country').descendant_level('City').name
    end

    it "should get level annotations" do
      assert_equal({'foo' => 'bar'}, @cube.dimension('Customers').hierarchy.level('Country').annotations)
    end

    it "should get level empty annotations" do
      assert_equal({}, @cube.dimension('Gender').hierarchy.level('Gender').annotations)
    end

    it "should be visible" do
      assert @cube.dimension('Gender').hierarchy.level('Gender').visible?
    end

  end

  describe "members" do
    before(:all) do
      @cube = @olap.cube('Sales')
    end

    it "should return member for specified full name" do
      assert_equal 'All Genders', @cube.member('[Gender].[All Genders]').name
      assert_equal 'OR', @cube.member('[Customers].[USA].[OR]').name
    end

    it "should return all member caption" do
      assert_equal 'All Genders caption', @cube.member('[Gender].[All Genders]').caption
    end

    it "should return member caption from expression" do
      assert_equal(
        (%w(mysql oracle).include?(MONDRIAN_DRIVER) ? 'dummy' : 'F'),
        @cube.member('[Gender].[F]').caption)
    end

    it "should not return member for invalid full name" do
      assert_nil @cube.member('[Gender].[invalid]')
    end

    it "should return child members for member" do
      assert_equal ['F', 'M'], @cube.member('[Gender].[All Genders]').children.map(&:name)
      assert_equal(
        ["Albany", "Beaverton", "Corvallis", "Lake Oswego", "Lebanon", "Milwaukie",
        "Oregon City", "Portland", "Salem", "W. Linn", "Woodburn"],
        @cube.member('[Customers].[USA].[OR]').children.map(&:name))
    end

    it "should return empty children array if member does not have children" do
      assert_empty @cube.member('[Gender].[F]').children
    end

    it "should return children count for member" do
      assert_equal 2, @cube.member('[Gender].[All Genders]').children_count
      assert_equal 11, @cube.member('[Customers].[USA].[OR]').children_count
      assert_equal 0, @cube.member('[Gender].[F]').children_count
    end

    it "should return member level" do
      assert_equal 'Country', @cube.member('[Customers].[USA]').level.name
    end

    it "should return member depth" do
      assert_equal 0, @cube.member('[Customers].[All Customers]').depth
      assert_equal 1, @cube.member('[Customers].[USA]').depth
      assert_equal 2, @cube.member('[Customers].[USA].[CA]').depth
    end

    it "should return descendants for member at specified level" do
      assert_equal(
        ["San Andres", "Santa Anita", "Santa Fe", "Tixapan", "Acapulco", "Guadalajara",
        "Mexico City", "Tlaxiaco", "La Cruz", "Orizaba", "Merida", "Camacho", "Hidalgo"],
        @cube.member('[Customers].[Mexico]').descendants_at_level('City').map(&:name))
    end

    it "should not return descendants for member when upper level specified" do
      assert_nil @cube.member('[Customers].[Mexico].[DF]').descendants_at_level('Country')
    end

    it "should be drillable when member has descendants" do
      assert @cube.member('[Customers].[USA]').drillable?
    end

    it "should not be drillable when member has no descendants" do
      assert_equal false, @cube.member('[Gender].[F]').drillable?
    end

    it "should not be drillable when member is calculated" do
      assert_equal false, @cube.member('[Customers].[Non-USA]').drillable?
    end

    it "should be calculated when member is calculated" do
      assert @cube.member('[Customers].[Non-USA]').calculated?
    end

    it "should be calculated when member is calculated in non-default hierarchy" do
      assert @cube.member('[Time.Weekly].[Last week]').calculated?
    end

    it "should not be calculated in query when calculated member defined in schema" do
      assert_equal false, @cube.member('[Customers].[Non-USA]').calculated_in_query?
    end

    it "should not be calculated when normal member" do
      assert_equal false, @cube.member('[Customers].[USA]').calculated?
    end

    it "should be all member when member is all member" do
      assert @cube.member('[Customers].[All Customers]').all_member?
    end

    it "should not be all member when member is not all member" do
      assert_equal false, @cube.member('[Customers].[USA]').all_member?
    end

    it "should get dimension type of standard dimension member" do
      assert_equal :standard, @cube.member('[Customers].[USA]').dimension_type
    end

    it "should get dimension type of measure" do
      assert_equal :measures, @cube.member('[Measures].[Unit Sales]').dimension_type
    end

    it "should get dimension type of time dimension member" do
      assert_equal :time, @cube.member('[Time].[2011]').dimension_type
    end

    it "should be visible when member is visible" do
      assert_equal true, @cube.member('[Measures].[Store Sales]').visible?
    end

    it "should not be visible when member is not visible" do
      assert_equal false, @cube.member('[Measures].[Store Cost]').visible?
    end

    it "should get measure annotations" do
      assert_equal({'foo' => 'bar'}, @cube.member('[Measures].[Unit Sales]').annotations)
    end

    it "should get measure empty annotations" do
      assert_equal({}, @cube.member('[Measures].[Store Sales]').annotations)
    end

    it "should get member empty annotations" do
      assert_equal({}, @cube.member('[Customers].[USA]').annotations)
    end
  end
end
