sudo: required
dist: focal

language: ruby
cache:
  - bundler
notifications:
  email: false
rvm:
  - jruby-9.4.12.0
addons:
  hosts:
    - oracle.vm
  apt:
    packages:
      - haveged
services:
  - mysql
  - postgresql
jdk:
  - openjdk8
  - openjdk11
  - openjdk17
env:
  global:
    - ORACLE_COOKIE=sqldev
    - ORACLE_FILE=oracle11g/xe/oracle-xe-11.2.0-1.0.x86_64.rpm.zip
    - ORACLE_HOME=/u01/app/oracle/product/11.2.0/xe
    - TNS_ADMIN=$ORACLE_HOME/network/admin
    - NLS_LANG=AMERICAN_AMERICA.AL32UTF8
    - ORACLE_BASE=/u01/app/oracle
    - LD_LIBRARY_PATH=$ORACLE_HOME/lib
    - PATH=$PATH:$ORACLE_HOME/jdbc/lib
    - DATABASE_VERSION=11.2.0.2
    - ORACLE_SID=XE
    - ORACLE_DATABASE_NAME=XE
    - DATABASE_NON_DEFAULT_TABLESPACE=USERS
    - JAVA_OPTS=-Xmx512m
    - JRUBY_OPTS="--dev"
branches:
  only:
    - master

before_install:
  - gem install bundler

install:
  - .travis/oracle/download.sh
  - .travis/oracle/install.sh
  - bundle install --jobs=3 --retry=3 --path vendor/bundle --binstubs

before_script:
  - .travis/create_db_schemas.sh

script:
  - .travis/run_tests.sh
