environment:
  JRUBY_OPTS: '--dev -J-Xmx1024m'
  matrix:
    - JRUBY_VERSION: "9.3.13.0"
      JAVA_VERSION: jdk11

services:
  - mssql2016

build: off

branches:
  only:
    - master

install:
  - ps: secedit /export /cfg c:\secpol.cfg
  - ps: (gc C:\secpol.cfg).replace("PasswordComplexity = 1", "PasswordComplexity = 0").replace("MinimumPasswordLength = 8", "MinimumPasswordLength = 0") | Out-File C:\secpol.cfg
  - ps: secedit /configure /db c:\windows\security\local.sdb /cfg c:\secpol.cfg /areas SECURITYPOLICY
  - ps: rm -force c:\secpol.cfg -confirm:$false
  - appveyor DownloadFile https://s3.amazonaws.com/jruby.org/downloads/%JRUBY_VERSION%/jruby-bin-%JRUBY_VERSION%.zip
  - 7z x jruby-bin-%JRUBY_VERSION%.zip -y > nul
  - del jruby-bin-%JRUBY_VERSION%.zip
  - appveyor DownloadFile https://download.microsoft.com/download/4/D/C/4DCD85FA-0041-4D2E-8DD9-833C1873978C/sqljdbc_7.2.1.0_enu.exe
  - 7z x sqljdbc_7.2.1.0_enu.exe -y > nul
  - copy sqljdbc_7.2\enu\mssql-jdbc-7.2.1.jre8.jar spec\support\jars\
  - SET JAVA_HOME=C:\Program Files\Java\%JAVA_VERSION%
  - SET PATH=C:\projects\mondrian-olap\jruby-%JRUBY_VERSION%\bin;%JAVA_HOME%\bin;%PATH%
  - gem install bundler
  - bundle install --jobs=1 --retry=3

before_test:
  - jruby -v
  - gem -v
  - bundle -v
  - sqlcmd -S "(local)" -U "sa" -P "Password12!" -Q "CREATE LOGIN mondrian_test WITH PASSWORD = 'mondrian_test'"
  - sqlcmd -S "(local)" -U "sa" -P "Password12!" -Q "ALTER SERVER ROLE [dbcreator] ADD MEMBER [mondrian_test]"
  - sqlcmd -S "(local)" -U "mondrian_test" -P "mondrian_test" -Q "CREATE DATABASE mondrian_test"
  - bundle exec rake db:create_data MONDRIAN_DRIVER=sqlserver

test_script:
  - bundle exec rake spec MONDRIAN_DRIVER=sqlserver
