# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{mondrian-olap}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Raimonds Simanovskis"]
  s.date = %q{2010-10-29}
  s.description = %q{mondrian-olap provides OLAP queries from relational databases using Mondrian OLAP engine.
}
  s.email = %q{raimonds.simanovskis@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE-Mondrian.html",
     "LICENSE.txt",
     "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     ".rspec",
     "Gemfile",
     "LICENSE-Mondrian.html",
     "LICENSE.txt",
     "README.rdoc",
     "Rakefile",
     "lib/mondrian-olap.rb",
     "lib/mondrian/jars/commons-collections-3.1.jar",
     "lib/mondrian/jars/commons-dbcp-1.2.1.jar",
     "lib/mondrian/jars/commons-logging-1.0.4.jar",
     "lib/mondrian/jars/commons-math-1.0.jar",
     "lib/mondrian/jars/commons-pool-1.2.jar",
     "lib/mondrian/jars/commons-vfs-1.0.jar",
     "lib/mondrian/jars/eigenbase-properties.jar",
     "lib/mondrian/jars/eigenbase-resgen.jar",
     "lib/mondrian/jars/eigenbase-xom.jar",
     "lib/mondrian/jars/javacup.jar",
     "lib/mondrian/jars/log4j-1.2.8.jar",
     "lib/mondrian/jars/log4j.properties",
     "lib/mondrian/jars/mondrian.jar",
     "lib/mondrian/jars/olap4j.jar",
     "lib/mondrian/olap.rb",
     "lib/mondrian/olap/connection.rb",
     "lib/mondrian/olap/cube.rb",
     "lib/mondrian/olap/query.rb",
     "lib/mondrian/olap/result.rb",
     "lib/mondrian/olap/schema.rb",
     "lib/mondrian/olap/schema_element.rb",
     "spec/connection_spec.rb",
     "spec/cube_spec.rb",
     "spec/fixtures/FoodMart.xml",
     "spec/fixtures/FoodMartCreateData.sql",
     "spec/query_spec.rb",
     "spec/schema_definition_spec.rb",
     "spec/spec_helper.rb",
     "spec/support/matchers/be_like.rb"
  ]
  s.homepage = %q{http://github.com/rsim/mondrian-olap}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Ruby DSL for Mondrian OLAP Java library}
  s.test_files = [
    "spec/connection_spec.rb",
     "spec/cube_spec.rb",
     "spec/query_spec.rb",
     "spec/schema_definition_spec.rb",
     "spec/spec_helper.rb",
     "spec/support/matchers/be_like.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<nokogiri>, [">= 1.4.3"])
    else
      s.add_dependency(%q<nokogiri>, [">= 1.4.3"])
    end
  else
    s.add_dependency(%q<nokogiri>, [">= 1.4.3"])
  end
end

